### ISSUE TITLE
Nice script

### ISSUE THREAD

**Issue by axisdos** [halojoy/QuickerBB#1]
Hey, nice forum software, however, can you please add more features and new style please. Thanks

**Comment by halojoy** [comment]
Thanks for your interest. I will not add more features, because features can slow down this fast forum. Later I will add more styles. The idea with this forum is it should be light and very fast. I like to keep it that way.<br /> For now I will only try to fix any bugs. If some people start to use, they can find bugs.

**Comment by axisdos** [comment]
What about just adding SEO Features?
